//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSistem_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFIRMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLFIRMA()
        {
            this.TBLURUN = new HashSet<TBLURUN>();
        }
    
        public int FIRMAID { get; set; }
        public string AD { get; set; }
        public string YETKILI { get; set; }
        public string YETKILITEL { get; set; }
        public string FIRMATEL { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUN> TBLURUN { get; set; }
    }
}
