//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSistem_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONEL
    {
        public int PERSONELID { get; set; }
        public string PERSONELAD { get; set; }
        public string PERSONELSOYAD { get; set; }
        public string KADI { get; set; }
        public string SIFRE { get; set; }
        public Nullable<bool> SUPERUSER { get; set; }
        public Nullable<int> SATISSAYISI { get; set; }
    }
}
