//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSistem_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATISLAR
    {
        public int SATISID { get; set; }
        public string URUN { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string TARIH { get; set; }
    }
}
