//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSistem_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        public int URUNID { get; set; }
        public string BARKOD { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public Nullable<decimal> ALISFIYAT { get; set; }
        public Nullable<decimal> SATISFIYAT { get; set; }
        public Nullable<int> STOK { get; set; }
        public string GELISTARIH { get; set; }
        public string SKT { get; set; }
    
        public virtual TBLFIRMA TBLFIRMA { get; set; }
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
    }
}
